name: CI Build

on:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - name: Setup .Net 5.0.x
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '5.0.x'
      - name: Setup .Net 6.0.x
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v2.4.0
      - name: Retore
        run: dotnet restore --nologo
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAYPAL_ClientId: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_ClientSecret: ${{ secrets.PAYPAL_CLIENT_SECRET }}
        run: dotnet test --nologo --no-build --configuration Release

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup .Net 5.0.x
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '5.0.x'
      - name: Setup .Net 6.0.x
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'
      - name: Tool restore with .Net
        run: dotnet tool restore
      - name: .Net Format
        run: dotnet format --no-restore --verify-no-changes -v diag
